// 오디오 카테고리 타입 (동적 - DB audio_categories 테이블에서 관리)
export type AudioCategory = string

// 오디오 아이템 타입 (Supabase audio_tracks 테이블과 일치)
export interface AudioItem {
  id: string // UUID
  title: string
  description: string | null
  filename: string
  emoji: string | null
  category: string
  subcategory?: string | null // 세분류 (예: '자기수용', '성장' 등)
  province?: string | null // 도 (trail_guide용, 예: 'gangwon')
  city?: string | null // 시군구 (trail_guide용, 예: 'chuncheon')
  trail_name?: string | null // 길 이름 (trail_guide용)
  duration?: number | null
  distance?: string | null // 거리 (trail_guide용, 예: '2.5km')
  walking_time?: string | null // 소요시간 (trail_guide용, 예: '약 40분')
  difficulty?: 'easy' | 'moderate' | 'hard' | null // 난이도
  is_active?: boolean
  order_index?: number
  created_at?: string
  updated_at?: string
}

// 재생 상태 타입
export type PlaybackState = 'playing' | 'paused' | 'stopped'

// 도 목록 (한글명 매핑)
export const PROVINCE_NAMES: Record<string, string> = {
  seoul: '서울특별시',
  gyeonggi: '경기도',
  incheon: '인천광역시',
  gangwon: '강원특별자치도',
  chungbuk: '충청북도',
  chungnam: '충청남도',
  sejong: '세종특별자치시',
  daejeon: '대전광역시',
  jeonbuk: '전북특별자치도',
  jeonnam: '전라남도',
  gwangju: '광주광역시',
  gyeongbuk: '경상북도',
  gyeongnam: '경상남도',
  daegu: '대구광역시',
  ulsan: '울산광역시',
  busan: '부산광역시',
  jeju: '제주특별자치도',
}

// 시군구 목록 (한글명 매핑)
export const CITY_NAMES: Record<string, string> = {
  // 강원도
  chuncheon: '춘천시',
  wonju: '원주시',
  gangneung: '강릉시',
  sokcho: '속초시',
  donghae: '동해시',
  samcheok: '삼척시',
  taebaek: '태백시',
  hongcheon: '홍천군',
  hoengseong: '횡성군',
  yeongwol: '영월군',
  pyeongchang: '평창군',
  jeongseon: '정선군',
  cheorwon: '철원군',
  hwacheon: '화천군',
  yanggu: '양구군',
  inje: '인제군',
  goseong: '고성군',
  yangyang: '양양군',

  // 경기도
  suwon: '수원시',
  seongnam: '성남시',
  goyang: '고양시',
  yongin: '용인시',
  bucheon: '부천시',
  ansan: '안산시',
  anyang: '안양시',
  namyangju: '남양주시',
  hwaseong: '화성시',
  pyeongtaek: '평택시',
  uijeongbu: '의정부시',
  siheung: '시흥시',
  paju: '파주시',
  gimpo: '김포시',
  gwangmyeong: '광명시',
  gwangju_gg: '광주시',
  gunpo: '군포시',
  hanam: '하남시',
  osan: '오산시',
  icheon: '이천시',
  anseong: '안성시',
  uiwang: '의왕시',
  yangpyeong: '양평군',
  yeoju: '여주시',
  gwacheon: '과천시',
  guri: '구리시',
  pocheon: '포천시',
  dongducheon: '동두천시',
  yangju: '양주시',
  gapyeong: '가평군',
  yeoncheon: '연천군',

  // 충청북도
  cheongju: '청주시',
  chungju: '충주시',
  jecheon: '제천시',
  boeun: '보은군',
  okcheon: '옥천군',
  yeongdong: '영동군',
  jeungpyeong: '증평군',
  jincheon: '진천군',
  goesan: '괴산군',
  eumseong: '음성군',
  danyang: '단양군',

  // 충청남도
  cheonan: '천안시',
  gongju: '공주시',
  boryeong: '보령시',
  asan: '아산시',
  seosan: '서산시',
  nonsan: '논산시',
  gyeryong: '계룡시',
  dangjin: '당진시',
  geumsan: '금산군',
  buyeo: '부여군',
  seocheon: '서천군',
  cheongyang: '청양군',
  hongseong: '홍성군',
  yesan: '예산군',
  taean: '태안군',

  // 전북특별자치도
  jeonju: '전주시',
  gunsan: '군산시',
  iksan: '익산시',
  jeongeup: '정읍시',
  namwon: '남원시',
  gimje: '김제시',
  wanju: '완주군',
  jinan: '진안군',
  muju: '무주군',
  jangsu: '장수군',
  imsil: '임실군',
  sunchang: '순창군',
  gochang: '고창군',
  buan: '부안군',

  // 전라남도
  mokpo: '목포시',
  yeosu: '여수시',
  suncheon: '순천시',
  naju: '나주시',
  gwangyang: '광양시',
  damyang: '담양군',
  gokseong: '곡성군',
  gurye: '구례군',
  goheung: '고흥군',
  boseong: '보성군',
  hwasun: '화순군',
  jangheung: '장흥군',
  gangjin: '강진군',
  haenam: '해남군',
  yeongam: '영암군',
  muan: '무안군',
  hampyeong: '함평군',
  yeonggwang: '영광군',
  jangseong: '장성군',
  wando: '완도군',
  jindo: '진도군',
  sinan: '신안군',

  // 경상북도
  pohang: '포항시',
  gyeongju: '경주시',
  gimcheon: '김천시',
  andong: '안동시',
  gumi: '구미시',
  yeongju: '영주시',
  yeongcheon: '영천시',
  sangju: '상주시',
  mungyeong: '문경시',
  gyeongsan: '경산시',
  uiseong: '의성군',
  cheongsong: '청송군',
  yeongyang: '영양군',
  yeongdeok: '영덕군',
  cheongdo: '청도군',
  goryeong: '고령군',
  seongju: '성주군',
  chilgok: '칠곡군',
  yecheon: '예천군',
  bonghwa: '봉화군',
  uljin: '울진군',
  ulleung: '울릉군',
  gunwi: '군위군',

  // 경상남도
  changwon: '창원시',
  jinju: '진주시',
  tongyeong: '통영시',
  sacheon: '사천시',
  gimhae: '김해시',
  miryang: '밀양시',
  geoje: '거제시',
  yangsan: '양산시',
  uiryeong: '의령군',
  haman: '함안군',
  changnyeong: '창녕군',
  goseong_gn: '고성군',
  namhae: '남해군',
  hadong: '하동군',
  sancheong: '산청군',
  hamyang: '함양군',
  geochang: '거창군',
  hapcheon: '합천군',

  // 제주특별자치도
  jeju_city: '제주시',
  seogwipo: '서귀포시',

  // 서울특별시
  jongno: '종로구',
  jung: '중구',
  yongsan: '용산구',
  seongdong: '성동구',
  gwangjin: '광진구',
  dongdaemun: '동대문구',
  jungnang: '중랑구',
  seongbuk: '성북구',
  gangbuk: '강북구',
  dobong: '도봉구',
  nowon: '노원구',
  eunpyeong: '은평구',
  seodaemun: '서대문구',
  mapo: '마포구',
  yangcheon: '양천구',
  gangseo: '강서구',
  guro: '구로구',
  geumcheon: '금천구',
  yeongdeungpo: '영등포구',
  dongjak: '동작구',
  gwanak: '관악구',
  seocho: '서초구',
  gangnam: '강남구',
  songpa: '송파구',
  gangdong: '강동구',

  // 인천광역시
  jung_ic: '중구',
  dong_ic: '동구',
  michuhol: '미추홀구',
  yeonsu: '연수구',
  namdong: '남동구',
  bupyeong: '부평구',
  gyeyang: '계양구',
  seo_ic: '서구',
  ganghwa: '강화군',
  ongjin: '옹진군',

  // 대전광역시
  dong_dj: '동구',
  jung_dj: '중구',
  seo_dj: '서구',
  yuseong: '유성구',
  daedeok: '대덕구',

  // 대구광역시
  jung_dg: '중구',
  dong_dg: '동구',
  seo_dg: '서구',
  nam_dg: '남구',
  buk_dg: '북구',
  suseong: '수성구',
  dalseo: '달서구',
  dalseong: '달성군',

  // 광주광역시
  dong_gj: '동구',
  seo_gj: '서구',
  nam_gj: '남구',
  buk_gj: '북구',
  gwangsan: '광산구',

  // 울산광역시
  jung_us: '중구',
  nam_us: '남구',
  dong_us: '동구',
  buk_us: '북구',
  ulju: '울주군',

  // 부산광역시
  jung_bs: '중구',
  seo_bs: '서구',
  dong_bs: '동구',
  yeongdo: '영도구',
  busanjin: '부산진구',
  dongnae: '동래구',
  nam_bs: '남구',
  buk_bs: '북구',
  haeundae: '해운대구',
  saha: '사하구',
  geumjeong: '금정구',
  gangseo_bs: '강서구',
  yeonje: '연제구',
  suyeong: '수영구',
  sasang: '사상구',
  gijang: '기장군',

  // 세종특별자치시
  sejong_city: '세종시',
}

// 시도별 시군구 매핑 (오디오 폼 드롭다운용)
export const PROVINCE_CITY_MAP: Record<string, { value: string; label: string }[]> = {
  seoul: [
    { value: 'jongno', label: '종로구' },
    { value: 'jung', label: '중구' },
    { value: 'yongsan', label: '용산구' },
    { value: 'seongdong', label: '성동구' },
    { value: 'gwangjin', label: '광진구' },
    { value: 'dongdaemun', label: '동대문구' },
    { value: 'jungnang', label: '중랑구' },
    { value: 'seongbuk', label: '성북구' },
    { value: 'gangbuk', label: '강북구' },
    { value: 'dobong', label: '도봉구' },
    { value: 'nowon', label: '노원구' },
    { value: 'eunpyeong', label: '은평구' },
    { value: 'seodaemun', label: '서대문구' },
    { value: 'mapo', label: '마포구' },
    { value: 'yangcheon', label: '양천구' },
    { value: 'gangseo', label: '강서구' },
    { value: 'guro', label: '구로구' },
    { value: 'geumcheon', label: '금천구' },
    { value: 'yeongdeungpo', label: '영등포구' },
    { value: 'dongjak', label: '동작구' },
    { value: 'gwanak', label: '관악구' },
    { value: 'seocho', label: '서초구' },
    { value: 'gangnam', label: '강남구' },
    { value: 'songpa', label: '송파구' },
    { value: 'gangdong', label: '강동구' },
  ],
  gyeonggi: [
    { value: 'suwon', label: '수원시' },
    { value: 'seongnam', label: '성남시' },
    { value: 'goyang', label: '고양시' },
    { value: 'yongin', label: '용인시' },
    { value: 'bucheon', label: '부천시' },
    { value: 'ansan', label: '안산시' },
    { value: 'anyang', label: '안양시' },
    { value: 'namyangju', label: '남양주시' },
    { value: 'hwaseong', label: '화성시' },
    { value: 'pyeongtaek', label: '평택시' },
    { value: 'uijeongbu', label: '의정부시' },
    { value: 'siheung', label: '시흥시' },
    { value: 'paju', label: '파주시' },
    { value: 'gimpo', label: '김포시' },
    { value: 'gwangmyeong', label: '광명시' },
    { value: 'gwangju_gg', label: '광주시' },
    { value: 'gunpo', label: '군포시' },
    { value: 'hanam', label: '하남시' },
    { value: 'osan', label: '오산시' },
    { value: 'icheon', label: '이천시' },
    { value: 'anseong', label: '안성시' },
    { value: 'uiwang', label: '의왕시' },
    { value: 'yangpyeong', label: '양평군' },
    { value: 'yeoju', label: '여주시' },
    { value: 'gwacheon', label: '과천시' },
    { value: 'guri', label: '구리시' },
    { value: 'pocheon', label: '포천시' },
    { value: 'dongducheon', label: '동두천시' },
    { value: 'yangju', label: '양주시' },
    { value: 'gapyeong', label: '가평군' },
    { value: 'yeoncheon', label: '연천군' },
  ],
  incheon: [
    { value: 'jung_ic', label: '중구' },
    { value: 'dong_ic', label: '동구' },
    { value: 'michuhol', label: '미추홀구' },
    { value: 'yeonsu', label: '연수구' },
    { value: 'namdong', label: '남동구' },
    { value: 'bupyeong', label: '부평구' },
    { value: 'gyeyang', label: '계양구' },
    { value: 'seo_ic', label: '서구' },
    { value: 'ganghwa', label: '강화군' },
    { value: 'ongjin', label: '옹진군' },
  ],
  gangwon: [
    { value: 'chuncheon', label: '춘천시' },
    { value: 'wonju', label: '원주시' },
    { value: 'gangneung', label: '강릉시' },
    { value: 'sokcho', label: '속초시' },
    { value: 'donghae', label: '동해시' },
    { value: 'samcheok', label: '삼척시' },
    { value: 'taebaek', label: '태백시' },
    { value: 'hongcheon', label: '홍천군' },
    { value: 'hoengseong', label: '횡성군' },
    { value: 'yeongwol', label: '영월군' },
    { value: 'pyeongchang', label: '평창군' },
    { value: 'jeongseon', label: '정선군' },
    { value: 'cheorwon', label: '철원군' },
    { value: 'hwacheon', label: '화천군' },
    { value: 'yanggu', label: '양구군' },
    { value: 'inje', label: '인제군' },
    { value: 'goseong', label: '고성군' },
    { value: 'yangyang', label: '양양군' },
  ],
  chungbuk: [
    { value: 'cheongju', label: '청주시' },
    { value: 'chungju', label: '충주시' },
    { value: 'jecheon', label: '제천시' },
    { value: 'boeun', label: '보은군' },
    { value: 'okcheon', label: '옥천군' },
    { value: 'yeongdong', label: '영동군' },
    { value: 'jeungpyeong', label: '증평군' },
    { value: 'jincheon', label: '진천군' },
    { value: 'goesan', label: '괴산군' },
    { value: 'eumseong', label: '음성군' },
    { value: 'danyang', label: '단양군' },
  ],
  chungnam: [
    { value: 'cheonan', label: '천안시' },
    { value: 'gongju', label: '공주시' },
    { value: 'boryeong', label: '보령시' },
    { value: 'asan', label: '아산시' },
    { value: 'seosan', label: '서산시' },
    { value: 'nonsan', label: '논산시' },
    { value: 'gyeryong', label: '계룡시' },
    { value: 'dangjin', label: '당진시' },
    { value: 'geumsan', label: '금산군' },
    { value: 'buyeo', label: '부여군' },
    { value: 'seocheon', label: '서천군' },
    { value: 'cheongyang', label: '청양군' },
    { value: 'hongseong', label: '홍성군' },
    { value: 'yesan', label: '예산군' },
    { value: 'taean', label: '태안군' },
  ],
  sejong: [
    { value: 'sejong_city', label: '세종시' },
  ],
  daejeon: [
    { value: 'dong_dj', label: '동구' },
    { value: 'jung_dj', label: '중구' },
    { value: 'seo_dj', label: '서구' },
    { value: 'yuseong', label: '유성구' },
    { value: 'daedeok', label: '대덕구' },
  ],
  jeonbuk: [
    { value: 'jeonju', label: '전주시' },
    { value: 'gunsan', label: '군산시' },
    { value: 'iksan', label: '익산시' },
    { value: 'jeongeup', label: '정읍시' },
    { value: 'namwon', label: '남원시' },
    { value: 'gimje', label: '김제시' },
    { value: 'wanju', label: '완주군' },
    { value: 'jinan', label: '진안군' },
    { value: 'muju', label: '무주군' },
    { value: 'jangsu', label: '장수군' },
    { value: 'imsil', label: '임실군' },
    { value: 'sunchang', label: '순창군' },
    { value: 'gochang', label: '고창군' },
    { value: 'buan', label: '부안군' },
  ],
  jeonnam: [
    { value: 'mokpo', label: '목포시' },
    { value: 'yeosu', label: '여수시' },
    { value: 'suncheon', label: '순천시' },
    { value: 'naju', label: '나주시' },
    { value: 'gwangyang', label: '광양시' },
    { value: 'damyang', label: '담양군' },
    { value: 'gokseong', label: '곡성군' },
    { value: 'gurye', label: '구례군' },
    { value: 'goheung', label: '고흥군' },
    { value: 'boseong', label: '보성군' },
    { value: 'hwasun', label: '화순군' },
    { value: 'jangheung', label: '장흥군' },
    { value: 'gangjin', label: '강진군' },
    { value: 'haenam', label: '해남군' },
    { value: 'yeongam', label: '영암군' },
    { value: 'muan', label: '무안군' },
    { value: 'hampyeong', label: '함평군' },
    { value: 'yeonggwang', label: '영광군' },
    { value: 'jangseong', label: '장성군' },
    { value: 'wando', label: '완도군' },
    { value: 'jindo', label: '진도군' },
    { value: 'sinan', label: '신안군' },
  ],
  gwangju: [
    { value: 'dong_gj', label: '동구' },
    { value: 'seo_gj', label: '서구' },
    { value: 'nam_gj', label: '남구' },
    { value: 'buk_gj', label: '북구' },
    { value: 'gwangsan', label: '광산구' },
  ],
  gyeongbuk: [
    { value: 'pohang', label: '포항시' },
    { value: 'gyeongju', label: '경주시' },
    { value: 'gimcheon', label: '김천시' },
    { value: 'andong', label: '안동시' },
    { value: 'gumi', label: '구미시' },
    { value: 'yeongju', label: '영주시' },
    { value: 'yeongcheon', label: '영천시' },
    { value: 'sangju', label: '상주시' },
    { value: 'mungyeong', label: '문경시' },
    { value: 'gyeongsan', label: '경산시' },
    { value: 'uiseong', label: '의성군' },
    { value: 'cheongsong', label: '청송군' },
    { value: 'yeongyang', label: '영양군' },
    { value: 'yeongdeok', label: '영덕군' },
    { value: 'cheongdo', label: '청도군' },
    { value: 'goryeong', label: '고령군' },
    { value: 'seongju', label: '성주군' },
    { value: 'chilgok', label: '칠곡군' },
    { value: 'yecheon', label: '예천군' },
    { value: 'bonghwa', label: '봉화군' },
    { value: 'uljin', label: '울진군' },
    { value: 'ulleung', label: '울릉군' },
    { value: 'gunwi', label: '군위군' },
  ],
  gyeongnam: [
    { value: 'changwon', label: '창원시' },
    { value: 'jinju', label: '진주시' },
    { value: 'tongyeong', label: '통영시' },
    { value: 'sacheon', label: '사천시' },
    { value: 'gimhae', label: '김해시' },
    { value: 'miryang', label: '밀양시' },
    { value: 'geoje', label: '거제시' },
    { value: 'yangsan', label: '양산시' },
    { value: 'uiryeong', label: '의령군' },
    { value: 'haman', label: '함안군' },
    { value: 'changnyeong', label: '창녕군' },
    { value: 'goseong_gn', label: '고성군' },
    { value: 'namhae', label: '남해군' },
    { value: 'hadong', label: '하동군' },
    { value: 'sancheong', label: '산청군' },
    { value: 'hamyang', label: '함양군' },
    { value: 'geochang', label: '거창군' },
    { value: 'hapcheon', label: '합천군' },
  ],
  daegu: [
    { value: 'jung_dg', label: '중구' },
    { value: 'dong_dg', label: '동구' },
    { value: 'seo_dg', label: '서구' },
    { value: 'nam_dg', label: '남구' },
    { value: 'buk_dg', label: '북구' },
    { value: 'suseong', label: '수성구' },
    { value: 'dalseo', label: '달서구' },
    { value: 'dalseong', label: '달성군' },
  ],
  ulsan: [
    { value: 'jung_us', label: '중구' },
    { value: 'nam_us', label: '남구' },
    { value: 'dong_us', label: '동구' },
    { value: 'buk_us', label: '북구' },
    { value: 'ulju', label: '울주군' },
  ],
  busan: [
    { value: 'jung_bs', label: '중구' },
    { value: 'seo_bs', label: '서구' },
    { value: 'dong_bs', label: '동구' },
    { value: 'yeongdo', label: '영도구' },
    { value: 'busanjin', label: '부산진구' },
    { value: 'dongnae', label: '동래구' },
    { value: 'nam_bs', label: '남구' },
    { value: 'buk_bs', label: '북구' },
    { value: 'haeundae', label: '해운대구' },
    { value: 'saha', label: '사하구' },
    { value: 'geumjeong', label: '금정구' },
    { value: 'gangseo_bs', label: '강서구' },
    { value: 'yeonje', label: '연제구' },
    { value: 'suyeong', label: '수영구' },
    { value: 'sasang', label: '사상구' },
    { value: 'gijang', label: '기장군' },
  ],
  jeju: [
    { value: 'jeju_city', label: '제주시' },
    { value: 'seogwipo', label: '서귀포시' },
  ],
}

// 난이도 라벨
export const DIFFICULTY_LABELS = {
  easy: { label: '쉬움', color: 'text-green-600', bg: 'bg-green-100' },
  moderate: { label: '보통', color: 'text-yellow-600', bg: 'bg-yellow-100' },
  hard: { label: '어려움', color: 'text-red-600', bg: 'bg-red-100' },
}
